name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mypy--type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install mypy
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      - name: Run type checking
        run: mypy src

  lint-and-format:
    runs-on: ubuntu-latest
    needs: mypy--type-check
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install ruff black
      - name: Lint with Ruff
        run: ruff check src tests
      - name: Check formatting with Black
        run: black --check src tests

  pytest--tests:
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: python -m pytest

  run-predict:
    runs-on: ubuntu-latest
    needs: pytest--tests
    steps:
      - uses: actions/checkout@v4
      - name: Run prediction script
        run: python src/predict.py "I love this movie!"

  docker--build-and-push:
    runs-on: ubuntu-latest
    needs: run-predict
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t ghcr.io/mani7982/sentiment-analysis-project:latest .
      - name: Push Docker image
        run: docker push ghcr.io/mani7982/sentiment-analysis-project:latest

  slack--notify:
    runs-on: ubuntu-latest
    needs: docker--build-and-push
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": "✅ CI/CD pipeline completed successfully for sentiment-analysis-project!"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
